# This Dockerfile sets up a Rust development environment
FROM mcr.microsoft.com/devcontainers/rust:0-1.60

# [Optional] Install additional OS packages
# RUN apt-get update && apt-get install -y --no-install-recommends <your-package-list-here>

# [Optional] Install additional Rust components
# RUN rustup component add <your-component-list-here>