# Use the existing Rust Dev Container image
FROM mcr.microsoft.com/devcontainers/rust:0-1.60

# Set the user to vscode (default user in the dev container)
USER vscode

# [Optional] Install additional OS packages
# RUN apt-get update && apt-get install -y --no-install-recommends <your-package-list-here>

# [Optional] Install additional Rust components
# RUN rustup component add <your-component-list-here>